os: linux
arch: x86_64
dist: bionic
sudo: false
language: cpp
compiler:
  - g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
install:
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
script:
  - make
  - ls -la
  - ./abstractfactory
